from .utils.settings import Settings


MIN_PLAYERS = 1
MAX_PLAYERS = 16

MIN_NAME_LEN = 1
MAX_NAME_LEN = 16

MIN_GAME_DURATION = 1 * 60
MAX_GAME_DURATION = 30 * 60

MIN_DEATH_DURATION = 1
MAX_DEATH_DURATION = 30

MIN_SHOTS_IN_BATCH = 1
MAX_SHOTS_IN_BATCH = 30

MIN_FN = 0
MAX_FN = 3

MAX_EVENTS = 16

SCORE_KILL_OPPONENTS = 100
SCORE_KILL_PLAYMATE = -50

core_settings = Settings(__name__, 'CORE')
